name: Test and build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  set-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  call-pytest-workflow:
    needs: set-environment
    uses: ASFHyP3/actions/.github/workflows/reusable-pytest.yml@v0.21.0
    permissions:
      contents: read
    with:
      local_package_name: hyp3_akfire_safe
      python_versions: >-
        ["3.10", "3.11", "3.12"]
