name: Test and build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  call-pytest-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-pytest.yml@v0.21.0
    permissions:
      contents: read
    with:
      local_package_name: hyp3_akfire_safe
      python_versions: >-
        ["3.10", "3.11", "3.12"]
    
